[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
license = "MIT OR Apache-2.0"
name = "demo"
version = "0.1.0"

[dependencies]
cortex-m = "0.2.4"
cortex-m-rt = "0.2.0"
stm32f100 = { path = "../stm32f100" }

[profile.release]
lto = true
